const KEY='osadnik-v02';
const defs={hq:['Ratusz',90,80,70],wood:['Tartak',70,90,60],clay:['Cegielnia',90,70,60],iron:['Huta żelaza',80,80,90],storage:['Magazyn',100,120,100],farm:['Zagroda',120,100,80],barracks:['Koszary',180,140,120]};
const villages=[{id:'v1',x:1,y:1,p:120,def:8},{id:'v2',x:5,y:2,p:180,def:14},{id:'v3',x:2,y:5,p:260,def:22},{id:'v4',x:6,y:6,p:390,def:35},{id:'v5',x:0,y:4,p:520,def:50}];
const fresh=()=>({res:{wood:900,clay:900,iron:800},build:{hq:1,wood:1,clay:1,iron:1,storage:1,farm:1,barracks:1},army:{spear:25,sword:8},owned:[],marches:[],reports:[{t:'Witaj w Osadniku v0.2!',d:'Na mapie możesz teraz atakować opuszczone wioski. Każda kolejna jest trudniejsza.'}],last:Date.now()});
let s;try{s=JSON.parse(localStorage.getItem(KEY))||fresh()}catch(e){s=fresh()}if(!s.owned)s.owned=[];if(!s.marches)s.marches=[];
function cap(){return 1000+s.build.storage*1000}function tick(){let n=Date.now(),h=(n-s.last)/3600000;['wood','clay','iron'].forEach(x=>s.res[x]=Math.min(cap(),s.res[x]+h*(100+s.build[x]*100)*(1+s.owned.length*.2)));s.last=n;resolveMarches(n);drawRes()}function drawRes(){document.querySelector('#resources').innerHTML=`Drewno: ${Math.floor(s.res.wood)} | Glina: ${Math.floor(s.res.clay)} | Żelazo: ${Math.floor(s.res.iron)} | Wioski: ${1+s.owned.length}`}
function cost(k){let d=defs[k],m=Math.pow(1.45,s.build[k]-1);return d.slice(1).map(v=>Math.floor(v*m))}function can(c){return s.res.wood>=c[0]&&s.res.clay>=c[1]&&s.res.iron>=c[2]}
function upgrade(k){let c=cost(k);if(!can(c))return alert('Brakuje surowców.');s.res.wood-=c[0];s.res.clay-=c[1];s.res.iron-=c[2];s.build[k]++;save();render('buildings')}
function save(){s.last=Date.now();localStorage.setItem(KEY,JSON.stringify(s));drawRes()}
function target(id){return villages.find(v=>v.id===id)}
function openAttack(id){let v=target(id);if(s.owned.includes(id))return alert('Ta wioska należy już do Ciebie.');let sp=prompt(`Atak na wioskę ${v.p} pkt. Obrona: ${v.def}\nIlu pikinierów wysłać?`,Math.min(10,s.army.spear));if(sp===null)return;let sw=prompt('Ilu mieczników wysłać?',Math.min(3,s.army.sword));sp=Math.max(0,Math.min(s.army.spear,parseInt(sp)||0));sw=Math.max(0,Math.min(s.army.sword,parseInt(sw)||0));if(sp+sw<1)return alert('Musisz wysłać wojsko.');s.army.spear-=sp;s.army.sword-=sw;let dist=Math.hypot(v.x-3,v.y-3),sec=Math.max(8,Math.round(dist*8));s.marches.push({id:Date.now(),target:id,spear:sp,sword:sw,end:Date.now()+sec*1000});s.reports.unshift({t:'Wojska wyruszyły',d:`${sp} pikinierów i ${sw} mieczników maszeruje na wioskę ${v.p} pkt. Czas marszu: ${sec}s.`});save();render('map')}
function resolveMarches(n){let done=s.marches.filter(m=>m.end<=n);if(!done.length)return;done.forEach(m=>battle(m));s.marches=s.marches.filter(m=>m.end>n);save();if(document.querySelector('.map'))render('map')}
function battle(m){let v=target(m.target),attack=m.spear*1+m.sword*1.35,def=v.def*(.85+Math.random()*.3),win=attack>def,ratio=Math.min(.9,def/Math.max(1,attack)*.65),lostS=Math.min(m.spear,Math.round(m.spear*ratio)),lostW=Math.min(m.sword,Math.round(m.sword*ratio));if(win){let rs=m.spear-lostS,rw=m.sword-lostW;s.army.spear+=rs;s.army.sword+=rw;if(!s.owned.includes(v.id))s.owned.push(v.id);s.res.wood=Math.min(cap(),s.res.wood+v.p);s.res.clay=Math.min(cap(),s.res.clay+v.p);s.res.iron=Math.min(cap(),s.res.iron+Math.round(v.p*.7));s.reports.unshift({t:'🏆 Zwycięstwo!',d:`Zdobyto wioskę ${v.p} pkt. Straty: ${lostS} pikinierów, ${lostW} mieczników. Ocalałe wojska wróciły do osady.`})}else{s.reports.unshift({t:'💀 Porażka',d:`Atak na wioskę ${v.p} pkt został odparty. Utracono wysłane oddziały.`})}}
function render(v='village'){tick();let a=document.querySelector('#app');if(v==='village')a.innerHTML=`<section class="hero"><h1>Wioska Osadnika</h1><p>Rozwijaj królestwo, rekrutuj wojska i podbijaj okoliczne osady.</p></section><div class="grid"><div class="card"><h3>Produkcja / h</h3><p>Drewno ${Math.round((100+s.build.wood*100)*(1+s.owned.length*.2))}<br>Glina ${Math.round((100+s.build.clay*100)*(1+s.owned.length*.2))}<br>Żelazo ${Math.round((100+s.build.iron*100)*(1+s.owned.length*.2))}</p></div><div class="card"><h3>Armia</h3><p>Pikinierzy: ${s.army.spear}<br>Miecznicy: ${s.army.sword}</p></div><div class="card"><h3>Królestwo</h3><p>Wioski: ${1+s.owned.length}<br>Podbite: ${s.owned.length}/5</p></div></div>`;
if(v==='buildings')a.innerHTML=`<h1>Budynki</h1><div class="grid">${Object.keys(defs).map(k=>{let c=cost(k);return `<div class="card"><h3>${defs[k][0]} — poziom ${s.build[k]}</h3><div class="cost">Koszt: ${c[0]} drewna, ${c[1]} gliny, ${c[2]} żelaza</div><button onclick="upgrade('${k}')">Rozbuduj</button></div>`}).join('')}</div>`;
if(v==='army')a.innerHTML=`<h1>Koszary</h1><div class="grid"><div class="card"><h3>Pikinier</h3><p>Atak 1.0</p><div class="cost">50 drewna / 30 gliny / 10 żelaza</div><button onclick="train('spear')">Rekrutuj</button><b> Masz: ${s.army.spear}</b></div><div class="card"><h3>Miecznik</h3><p>Atak 1.35</p><div class="cost">30 / 30 / 70</div><button onclick="train('sword')">Rekrutuj</button><b> Masz: ${s.army.sword}</b></div></div>`;
if(v==='map'){let cells='';for(let y=0;y<7;y++)for(let x=0;x<7;x++){let cl='',tx='',onclick='';if(x===3&&y===3){cl='mine';tx='🏰<br>Stolica'}else{let q=villages.find(q=>q.x===x&&q.y===y);if(q){let own=s.owned.includes(q.id);cl=own?'mine':'barbarian';tx=`${own?'🏰':'🏚'}<br>${q.p} pkt${own?'<br>Twoja':'<br>Obrona '+q.def}`;if(!own)onclick=`onclick="openAttack('${q.id}')" style="cursor:pointer"`;}else if(x===5&&y===5){cl='enemy';tx='⚔<br>Bot<br>750 pkt'}}cells+=`<div class="tile ${cl}" ${onclick}>${tx}</div>`}let marches=s.marches.map(m=>{let q=target(m.target);return `<div class="report">⚔ Atak na ${q.p} pkt — ${Math.max(0,Math.ceil((m.end-Date.now())/1000))}s — ${m.spear} pikinierów, ${m.sword} mieczników</div>`}).join('');a.innerHTML=`<h1>Mapa świata</h1><p>Kliknij opuszczoną wioskę, aby wysłać atak. Każda kolejna osada jest silniejsza.</p>${marches}<div class="map">${cells}</div>`}
if(v==='reports')a.innerHTML=`<h1>Raporty</h1>${s.reports.map(r=>`<div class="report"><b>${r.t}</b><br>${r.d}</div>`).join('')}`}
function train(t){let c=t==='spear'?[50,30,10]:[30,30,70];if(!can(c))return alert('Brakuje surowców.');s.res.wood-=c[0];s.res.clay-=c[1];s.res.iron-=c[2];s.army[t]++;save();render('army')}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>render(b.dataset.view));document.querySelector('#save').onclick=()=>{save();alert('Gra zapisana.')};document.querySelector('#reset').onclick=()=>{if(confirm('Rozpocząć nową grę?')){s=fresh();save();render()}};setInterval(()=>{tick();if(document.querySelector('.map'))render('map')},1000);render();