// Osadnik v0.2.8 — interaktywna mapa świata
const baseRenderV028=render;
const villageNames={v1:'Dębowy Bród',v2:'Kamienna Straż',v3:'Wilcze Pole',v4:'Żelazny Gród',v5:'Czarny Las'};
function distanceTo(v){return Math.hypot(v.x-3,v.y-3)}
function marchTime(v){return Math.max(8,Math.round(distanceTo(v)*8))}
function fmtTime(sec){let m=Math.floor(sec/60),s2=sec%60;return `${String(m).padStart(2,'0')}:${String(s2).padStart(2,'0')}`}
function openVillagePanel(id){let v=target(id),own=s.owned.includes(id),name=villageNames[id]||'Nieznana osada';document.querySelector('#villagePanel')?.remove();let el=document.createElement('div');el.id='villagePanel';el.className='villagePanel';el.innerHTML=`<button class="vpClose" onclick="this.parentElement.remove()">✕</button><div class="vpBanner ${own?'friendly':'neutral'}">${own?'⚜':'☗'}</div><h2>${name}</h2><div class="vpType">${own?'Twoja wioska':'Wioska barbarzyńska'}</div><div class="vpStats"><span><b>${v.p}</b>Punkty</span><span><b>${distanceTo(v).toFixed(1)}</b>Odległość</span><span><b>${fmtTime(marchTime(v))}</b>Marsz</span></div><div class="vpRow"><span>Właściciel</span><b>${own?'Królestwo Osadnika':'Barbarzyńcy'}</b></div><div class="vpRow"><span>Obrona</span><b>${own?'Garnizon':'około '+v.def}</b></div>${own?`<button class="vpAction secondary" onclick="this.parentElement.remove();render('village')">🏰 Przejdź do wioski</button>`:`<div class="vpActions"><button class="vpAction attack" onclick="this.closest('.villagePanel').remove();openAttack('${id}')">⚔ ATAK</button><button class="vpAction scout" onclick="scoutVillage('${id}')">👁 ZWIAD</button></div>`}`;document.querySelector('.mapStage').appendChild(el)}
function scoutVillage(id){let v=target(id);if((s.army.scout||0)<1)return alert('Potrzebujesz przynajmniej 1 zwiadowcy.');let name=villageNames[id]||'osada';s.reports.unshift({t:'👁 Raport zwiadowczy',d:`${name}: ${v.p} pkt, szacowana obrona ${v.def}, odległość ${distanceTo(v).toFixed(1)} pola, czas marszu ${fmtTime(marchTime(v))}.`});save();alert('Raport zwiadowczy zapisano w Raportach.')}
function mapHtmlV028(){let cells='';for(let y=0;y<7;y++)for(let x=0;x<7;x++){let q=villages.find(z=>z.x===x&&z.y===y),cls='',inner='';if(x===3&&y===3){cls='capital';inner=`<div class="mapVillage big"><span class="mapCastle">🏰</span><b>Stolica</b><small>${Object.values(s.build).reduce((a,b)=>a+b,0)*45} pkt</small><i class="flag blue"></i></div>`}else if(q){let own=s.owned.includes(q.id);cls=own?'owned':'barb';inner=`<button class="mapVillage ${q.p>=390?'large':''}" onclick="openVillagePanel('${q.id}')"><span class="mapCastle">${own?'🏰':'🏯'}</span><b>${villageNames[q.id]}</b><small>${q.p} pkt</small><i class="flag ${own?'blue':'gray'}"></i></button>`}else if(x===5&&y===5){cls='enemyCell';inner=`<div class="mapVillage large enemyVillage"><span class="mapCastle">🏯</span><b>Kruczy Gród</b><small>750 pkt</small><i class="flag red"></i></div>`}cells+=`<div class="worldCell ${cls}">${inner}</div>`}return `<div class="mapHeader"><div><h1>🗺️ Mapa świata</h1><p>Sektor 0|0 • kliknij osadę, aby otworzyć panel</p></div><div class="mapCoords">📍 Stolica [3|3]</div></div><div class="worldLegend"><span>🔵 Twoje</span><span>⚪ Barbarzyńcy</span><span>🔴 Bot</span></div>${s.marches.map(m=>`<div class="report marchReport">⚔️ Wojska w drodze <b>${Math.max(0,Math.ceil((m.end-Date.now())/1000))}s</b></div>`).join('')}<div class="mapStage"><div class="mapTerrain"><div class="mapRiver"></div><div class="mapRoad roadA"></div><div class="mapRoad roadB"></div><div class="mapGrid">${cells}</div></div></div>`}
function renderMapV028(){current='map';tick();let app=document.querySelector('#app');if(app)app.innerHTML=mapHtmlV028()}
render=function(v='village'){if(v==='map')return renderMapV028();return baseRenderV028(v)};
const mapButton=document.querySelector('[data-view="map"]');if(mapButton)mapButton.onclick=(e)=>{e.preventDefault();renderMapV028()};